"""Opt-in PostgreSQL package-play acceptance in owned ephemeral schemas only.

No .env, application startup, public-schema migration or real model call.
Set FUSION_POSTGRES_TEST_DATABASE_URL to the dedicated localhost sandbox and
PACKAGE_PLAY_POSTGRES_TEST_CONFIRM=CREATE_PACKAGE_PLAY_EPHEMERAL_SCHEMA.
Only --verbose and --collect-only are accepted; pytest paths/options cannot
escape the one integration module selected by this entry point.
"""
from __future__ import annotations

from contextlib import contextmanager
from dataclasses import dataclass
import os
from pathlib import Path
import re
import socket
import sys
from typing import Iterator, Mapping
from unittest.mock import patch
from uuid import uuid4

from sqlalchemy import Engine, create_engine, text


BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from scripts.test_fusion_postgres_budget import (
    CONFIRM_ENV as BUDGET_CONFIRM_ENV, REQUIRED_CONFIRMATION as BUDGET_CONFIRMATION,
    TEST_DATABASE_ENV, UnsafeTestDatabase, ValidatedTestDatabase,
    _disable_non_database_network_features, validate_test_database_environment,
)


CONFIRM_ENV = "PACKAGE_PLAY_POSTGRES_TEST_CONFIRM"
REQUIRED_CONFIRMATION = "CREATE_PACKAGE_PLAY_EPHEMERAL_SCHEMA"
SCHEMA_PREFIX = "package_play_it_"
SCHEMA_PATTERN = r"package_play_it_[0-9a-f]{32}"


def validate_environment(environ: Mapping[str, str] | None = None) -> ValidatedTestDatabase:
    values = os.environ if environ is None else environ
    if values.get(CONFIRM_ENV) != REQUIRED_CONFIRMATION:
        raise UnsafeTestDatabase(f"refusing database access: set {CONFIRM_ENV}={REQUIRED_CONFIRMATION}")
    if any(name.startswith("PG") for name in values):
        # libpq environment defaults such as PGHOSTADDR/PGSERVICE can redirect
        # a URL or load extra connection files. Only the explicit URL is used.
        raise UnsafeTestDatabase("refusing database access: libpq PG* environment overrides are not allowed")
    try:
        target = validate_test_database_environment(dict(values) | {BUDGET_CONFIRM_ENV: BUDGET_CONFIRMATION})
    except UnsafeTestDatabase as exc:
        raise UnsafeTestDatabase(str(exc)) from None
    if (target.url.host != "127.0.0.1" or target.url.database != "fusion_pg_it_sandbox"
            or target.url.username != "fusion_it" or target.url.port != 55432):
        raise UnsafeTestDatabase("refusing database access: the exact canonical sandbox identity is required")
    return target


def validate_schema_name(name: str) -> str:
    if type(name) is not str or re.fullmatch(SCHEMA_PATTERN, name) is None:
        raise UnsafeTestDatabase("refusing schema access: invalid owned ephemeral schema name")
    return name


def runner_options(args: list[str]) -> list[str]:
    if any(item not in {"--verbose", "--collect-only"} for item in args) or len(args) != len(set(args)):
        raise UnsafeTestDatabase("refusing runner arguments: only --verbose and --collect-only are supported")
    return list(args)


def database_connect_args(schema: str | None = None) -> dict:
    path = validate_schema_name(schema) if schema is not None else "pg_catalog"
    return {"hostaddr": "127.0.0.1", "connect_timeout": 5, "sslmode": "disable",
            "application_name": "package-play-postgres-it",
            "options": f"-c search_path={path} -c statement_timeout=15000 -c lock_timeout=5000"}


def _check_server(connection, target: ValidatedTestDatabase) -> None:
    database, user, read_only = connection.execute(text(
        "SELECT current_database(), current_user, current_setting('transaction_read_only')")).one()
    if database != target.database or user != "fusion_it" or read_only != "off":
        raise UnsafeTestDatabase("refusing schema access: connected sandbox identity or write mode differs")


def _schema_identity(connection, name: str):
    validate_schema_name(name)
    return connection.execute(text(
        "SELECT n.oid, pg_get_userbyid(n.nspowner) FROM pg_namespace n WHERE n.nspname=:name"),
        {"name": name}).one_or_none()


def drop_owned_schema(connection, *, name: str, oid: int, owner: str) -> None:
    validate_schema_name(name)
    if type(oid) is not int or oid <= 0 or owner != "fusion_it":
        raise UnsafeTestDatabase("refusing cleanup: invalid schema ownership receipt")
    identity = _schema_identity(connection, name)
    if identity is None:
        return
    if tuple(identity) != (oid, owner):
        raise UnsafeTestDatabase("refusing cleanup: schema identity or ownership changed")
    # The exact identifier is generated by this process and fully validated;
    # no prefix discovery, public-schema cleanup or caller-provided SQL exists.
    connection.execute(text(f'DROP SCHEMA "{name}" CASCADE'))


@dataclass(frozen=True)
class IsolatedPostgres:
    engine: Engine
    schema: str

    def assert_connection(self, connection) -> None:
        current, paths = connection.execute(text("SELECT current_schema(), current_schemas(false)")).one()
        if current != self.schema or list(paths) != [self.schema]:
            raise UnsafeTestDatabase("refusing migration: connection escaped the owned schema")


@contextmanager
def isolated_schema() -> Iterator[IsolatedPostgres]:
    target = validate_environment()
    name = validate_schema_name(SCHEMA_PREFIX + uuid4().hex)
    bootstrap = create_engine(target.url, connect_args=database_connect_args(),
                              pool_pre_ping=True, hide_parameters=True, echo=False)
    engine = None
    identity = None
    created = False
    try:
        with bootstrap.begin() as connection:
            _check_server(connection, target)
            connection.execute(text(f'CREATE SCHEMA "{name}"'))
            identity = _schema_identity(connection, name)
            if identity is None or identity[1] != "fusion_it":
                raise UnsafeTestDatabase("refusing schema access: ownership verification failed")
        created = True
        engine = create_engine(target.url, connect_args=database_connect_args(name),
                               pool_pre_ping=True, pool_size=8, max_overflow=0,
                               hide_parameters=True, echo=False)
        result = IsolatedPostgres(engine, name)
        with engine.connect() as connection:
            _check_server(connection, target)
            result.assert_connection(connection)
        yield result
    finally:
        if engine is not None:
            engine.dispose()
        try:
            if created:
                with bootstrap.begin() as connection:
                    _check_server(connection, target)
                    drop_owned_schema(connection, name=name, oid=identity[0], owner=identity[1])
                with bootstrap.connect() as connection:
                    if _schema_identity(connection, name) is not None:
                        raise UnsafeTestDatabase("ephemeral schema cleanup could not be verified")
        finally:
            bootstrap.dispose()


def _database_address(address: object) -> bool:
    return (isinstance(address, tuple) and len(address) >= 2
            and address[0] == "127.0.0.1" and type(address[1]) is int and address[1] == 55432)


@contextmanager
def database_only_network():
    connect, connect_ex = socket.socket.connect, socket.socket.connect_ex
    def guarded(original):
        def call(instance, address):
            if not _database_address(address):
                raise AssertionError("PostgreSQL acceptance must not contact non-database services")
            return original(instance, address)
        return call
    with patch("socket.socket.connect", guarded(connect)), patch("socket.socket.connect_ex", guarded(connect_ex)):
        yield


def main(args: list[str] | None = None) -> int:
    try:
        options = runner_options(sys.argv[1:] if args is None else args)
        target = validate_environment()
    except UnsafeTestDatabase as exc:
        print(str(exc), file=sys.stderr)
        return 2
    _disable_non_database_network_features()
    for key in ("PYTEST_ADDOPTS", "PYTEST_PLUGINS", "ARK_BASE_URL", "DASHSCOPE_BASE_URL"):
        os.environ.pop(key, None)
    sys.dont_write_bytecode = True
    print(f"Package-play PostgreSQL sandbox: {target.safe_label}")
    print("Only owned random schemas; paid/provider calls disabled; SDK replies are synthetic.")
    if "--collect-only" in options:
        print("Collection only: no database connection or migration will run.")
    import pytest
    suite = BACKEND / "tests/postgres_integration"
    with (patch("dotenv.load_dotenv", return_value=False), database_only_network(),
          patch("src.services.llm_service.OpenAILLMService.__init__",
                side_effect=AssertionError("Real provider clients are forbidden in PostgreSQL acceptance"))):
        return pytest.main([str(suite / "test_package_play_postgres.py"), f"--confcutdir={suite}",
                            "-c", os.devnull, f"--rootdir={BACKEND}", "-p", "no:cacheprovider",
                            "--maxfail=1", "--tb=short", "-q", *options])


if __name__ == "__main__":
    raise SystemExit(main())
